description: Le site d'information sur la mobilité électrique en Suisse romande
url: https://evromandie.ch

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

matomo:
  url: https://analytics.kilowhat.net/
  id: 31

main_menu:
  - title: Événements
    url: /evenements
  - title: Chaînes YouTube
    url: /youtube
  - title: Resources
    children:
      - title: Véhicules disponibles
        url: /vehicules
      - title: Réseaux et passes
        url: /reseaux
      - title: Glossaire
        url: /glossaire
      - title: Autres liens et ressources
        url: /ressources
  - title: À propos
    url: /a-propos
  - title: Discord
    url: /discord

forum_url: https://forum.evromandie.ch/

social_links:
  - title: YouTube
    url: https://www.youtube.com/channel/UCNGDiG3zqA-sUW0utDszY0Q
    label: EV Romandie
    icon: youtube-play
  - title: Flickr
    url: https://www.flickr.com/photos/evromandie/albums
    label: "@evromandie"
    icon: flickr
  - title: Twitter
    url: https://twitter.com/evromandie
    label: "@evromandie"
    icon: twitter
  - title: Facebook
    url: https://www.facebook.com/evromandie/
    label: "@evromandie"
    icon: facebook
  - title: GitHub
    url: https://github.com/evromandie
    label: evromandie
    icon: github
