description: Le site d'information sur la mobilité électrique en Suisse romande
url: https://evromandie.ch

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

matomo:
    url: https://analytics.kilowhat.net/
    id: 31

main_menu:
  - title: Événements
    url: /evenements
  - title: Réseaux et passes
    url: /reseaux
  - title: Liens et ressources
    url: /ressources
  - title: À propos
    url: /a-propos

forum_url: https://forum.evromandie.ch/

social_links:
  - title: YouTube
    url: https://www.youtube.com/channel/UCNGDiG3zqA-sUW0utDszY0Q
    label: EV Romandie
    icon: youtube-play
  - title: Flickr
    url: https://www.flickr.com/photos/evromandie/albums
    label: "@evromandie"
    icon: flickr
  - title: Twitter
    url: https://twitter.com/evromandie
    label: "@evromandie"
    icon: twitter
  - title: Facebook
    url: https://www.facebook.com/evromandie/
    label: "@evromandie"
    icon: facebook
  - title: GitHub
    url: https://github.com/evromandie
    label: evromandie
    icon: github
