description: Tout ce qu'il y a à connaître sur la mobilité électrique en Suisse romande
url: https://evromandie.ch

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

matomo:
    url: https://analytics.kilowhat.net/
    id: 31

main_menu:
  - title: Événements
    url: /evenements
  - title: Liens et ressources
    url: /ressources
  - title: À propos
    url: /a-propos

forum_url: https://forum.evromandie.ch/
